"""
intelligence/refactor_suggester.py
====================================
Module 10 — Refactoring suggestion generator.

╔══════════════════════════════════════════════════════════════════════════╗
║  IMPORTANT — READ-ONLY MODULE                                            ║
║                                                                          ║
║  This module has ONE responsibility: produce a Suggestion (text).        ║
║                                                                          ║
║  It NEVER:                                                               ║
║    • writes to any file on disk                                          ║
║    • calls git or any version-control tool                               ║
║    • modifies the Obsidian vault or any memory store                     ║
║    • executes or schedules any code change                               ║
║                                                                          ║
║  If you find yourself adding a write operation here, STOP.               ║
║  That logic belongs in a separate executor module that does not exist    ║
║  yet and must not be added without explicit human approval.              ║
╚══════════════════════════════════════════════════════════════════════════╝

Public API
----------
- :func:`suggest` — given a :class:`~intelligence.intelligence_types.Pattern`
  and a :class:`~intelligence.suggestion_store.SuggestionStore`, produce a
  :class:`~intelligence.intelligence_types.Suggestion`.

The suggestion text is generated by the AI using the ``"refactor_suggestion_v2"``
prompt template.  Few-shot examples are pulled from the store so the AI learns
from past accepted and rejected suggestions.
"""

from __future__ import annotations

# Sentinel — checked by tests and auditing tools.
_WRITES_FILES: bool = False

import logging
from typing import TYPE_CHECKING

# get_ai is imported at module level so tests can patch
# ``intelligence.refactor_suggester.get_ai`` directly.
from ai.ai_manager import get_ai
from intelligence.intelligence_types import Pattern, Suggestion

if TYPE_CHECKING:
    from intelligence.suggestion_store import SuggestionStore

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Priority mapping
# ---------------------------------------------------------------------------

_SEVERITY_TO_PRIORITY: dict[str, int] = {
    "critical": 1,
    "high": 2,
    "medium": 3,
    "low": 3,
}

_PROMPT_NAME = "refactor_suggestion_v2"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def suggest(
    pattern: Pattern,
    store: "SuggestionStore",
) -> Suggestion:
    """Generate a refactoring suggestion for *pattern*.

    This function is **advisory only**.  It calls the AI and returns a
    :class:`~intelligence.intelligence_types.Suggestion` with
    ``state="PENDING"``.  Nothing is persisted here — that is the
    responsibility of :mod:`intelligence.suggestion_store`.

    Parameters
    ----------
    pattern:
        The detected anti-pattern to generate a suggestion for.
    store:
        Used **read-only** here to fetch few-shot examples for the prompt.
        :func:`suggest` never calls any write method on the store.

    Returns
    -------
    Suggestion
        A fully-populated suggestion with ``state="PENDING"``.
        The ``suggestion_text`` field contains the raw AI response.

    Raises
    ------
    core.exceptions.AIError
        If the underlying AI call fails.  The caller
        (:mod:`intelligence.intelligence_engine`) catches this and logs it.
    """
    # --- Build few-shot context (read-only store access) ---
    accepted_examples = store.get_accepted_examples(n=3)
    rejected_examples = store.get_rejected_examples(n=3)

    past_accepted = _format_examples(accepted_examples, label="ACCEPTED")
    past_rejected = _format_examples(rejected_examples, label="REJECTED")
    pattern_desc = _format_pattern(pattern)

    # --- Call AI (produces text only — no side effects) ---
    suggestion_text = get_ai().complete(
        _PROMPT_NAME,
        {
            "pattern": pattern_desc,
            "past_accepted": past_accepted or "(none yet)",
            "past_rejected": past_rejected or "(none yet)",
        },
    )

    priority = _SEVERITY_TO_PRIORITY.get(pattern.severity, 3)

    suggestion = Suggestion(
        pattern_type=pattern.pattern_type,
        affected_files=list(pattern.affected_files),
        suggestion_text=suggestion_text,
        priority=priority,
        state="PENDING",
    )

    log.info(
        "[refactor_suggester] suggestion generated: id=%s pattern=%s priority=%d",
        suggestion.id,
        pattern.pattern_type,
        priority,
    )
    return suggestion


# ---------------------------------------------------------------------------
# Private helpers  (no I/O)
# ---------------------------------------------------------------------------

def _format_pattern(pattern: Pattern) -> str:
    """Render a :class:`Pattern` as a human-readable string for the prompt."""
    lines = [
        f"Type:     {pattern.pattern_type}",
        f"Severity: {pattern.severity}",
        f"Files:    {', '.join(pattern.affected_files)}",
        f"Summary:  {pattern.description}",
    ]
    if pattern.evidence:
        lines.append("Evidence:")
        for ev in pattern.evidence[:10]:   # cap at 10 to keep prompt tight
            lines.append(f"  • {ev}")
    return "\n".join(lines)


def _format_examples(examples: list[dict], *, label: str) -> str:
    """Render a list of example dicts into a numbered prompt block."""
    if not examples:
        return ""
    parts: list[str] = []
    for i, ex in enumerate(examples, start=1):
        suggestion_text = ex.get("suggestion_text", "")
        reason = ex.get("rejection_reason", "")
        pattern_type = ex.get("pattern_type", "")
        entry = f"{i}. [{label}] ({pattern_type})\n{suggestion_text}"
        if reason:
            entry += f"\n   Rejection reason: {reason}"
        parts.append(entry)
    return "\n\n".join(parts)
